ame: group18_analytics

version: 1.0
config-version: 2

profile: default

analysis-paths: ["analyses"]
macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  group18_analytics:
    staging:
      +materialized: table
      +schema: group18_stg_data

    marts:
      +materialized: table

      shared:
        +schema: conformed_dimensions
      
      illegal_parking_mart:
        +schema: group_18_illegal_parking_mart
      
      mvc_crashes_mart:
        +schema: group_18_mvc_crashes_mart

seeds:
  group18_analytics:
    nyc_zip_polygons:
      +schema: dbt_nhuang
      +column_types:
        zip_code: string
        borough: string
        geom_wkt: string
      shared: {}
