name: group18_analytics

version: 1.0
config-version: 2

profile: default

analysis-paths: ["analyses"]
macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  group18_analytics:
    staging:
      +materialized: table
      +schema: group18_stg_data

    marts:
      +materialized: table

      shared: {}

